// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PowerAppsAplication.Context;

#nullable disable

namespace PowerAppsAplication.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20240311153405_firstM")]
    partial class firstM
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("PowerAppsAplication.Models.Equipos", b =>
                {
                    b.Property<int>("PkEquipo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PkEquipo"), 1L, 1);

                    b.Property<string>("Departamento")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Descripcion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Estado")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LugarAsignado")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Marca")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Modelo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NoSerie")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PeriodoCalibracion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ProximaCalibracion")
                        .HasColumnType("datetime2");

                    b.Property<string>("Responsable")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UltimaCalibracion")
                        .HasColumnType("datetime2");

                    b.HasKey("PkEquipo");

                    b.ToTable("Equipos");
                });

            modelBuilder.Entity("PowerAppsAplication.Models.HistoricoEquipos", b =>
                {
                    b.Property<int>("PKHistoricoEquipos")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PKHistoricoEquipos"), 1L, 1);

                    b.Property<string>("Calibracion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("EquiposPkEquipo")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaMantenimiento")
                        .HasColumnType("datetime2");

                    b.Property<decimal?>("FechaReparacion")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("FkEquipo")
                        .HasColumnType("int");

                    b.Property<DateTime?>("MontoGastado")
                        .HasColumnType("datetime2");

                    b.Property<string>("Motivo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Reparacion")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PKHistoricoEquipos");

                    b.HasIndex("EquiposPkEquipo");

                    b.ToTable("HistoricoEquipos");
                });

            modelBuilder.Entity("PowerAppsAplication.Models.HistoricoEquipos", b =>
                {
                    b.HasOne("PowerAppsAplication.Models.Equipos", "Equipos")
                        .WithMany("HistoricoEquipos")
                        .HasForeignKey("EquiposPkEquipo");

                    b.Navigation("Equipos");
                });

            modelBuilder.Entity("PowerAppsAplication.Models.Equipos", b =>
                {
                    b.Navigation("HistoricoEquipos");
                });
#pragma warning restore 612, 618
        }
    }
}
