// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PowerAppsAplication.Context;

#nullable disable

namespace PowerAppsAplication.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20240322142854_FirstM")]
    partial class FirstM
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("PowerAppsAplication.Models.EPPTorres", b =>
                {
                    b.Property<int>("PkEPPTorres")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PkEPPTorres"), 1L, 1);

                    b.Property<bool>("Arnes5Posiciones")
                        .HasColumnType("bit");

                    b.Property<string>("BotasSeguridad")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CascoSeguridadBarbiquejo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ciudad")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Comentario")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ComentariosStatusArnes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CuerdaPosicionamiento")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("FechaFabricacionArnes")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaFabricacionCuerda")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaFabricacionShock")
                        .HasColumnType("datetime2");

                    b.Property<string>("Gerencia")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Guantes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Imagen1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Imagen2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImagenFirma")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("JefeDirecto")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LentesSeguridad")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MarcaArnes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Mosqueton")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NombreUsuario")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ShockAbsorbente")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SujetadorLineaVida")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PkEPPTorres");

                    b.ToTable("EPPTorres");
                });

            modelBuilder.Entity("PowerAppsAplication.Models.Equipos", b =>
                {
                    b.Property<int>("PkEquipo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PkEquipo"), 1L, 1);

                    b.Property<string>("Ciudad")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Departamento")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Descripcion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Estado")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Marca")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Modelo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NoSerie")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PeriodoCalibracion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ProximaCalibracion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ProximaMantenimiento")
                        .HasColumnType("datetime2");

                    b.Property<string>("Region")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Responsable")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UltimaCalibracion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("UltimoMantenimiento")
                        .HasColumnType("datetime2");

                    b.HasKey("PkEquipo");

                    b.ToTable("Equipos");
                });

            modelBuilder.Entity("PowerAppsAplication.Models.HistoricoEquipos", b =>
                {
                    b.Property<int>("PKHistoricoEquipos")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PKHistoricoEquipos"), 1L, 1);

                    b.Property<string>("CertificadoCalibracion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Comentarios")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Descripcion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("EquiposPkEquipo")
                        .HasColumnType("int");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime2");

                    b.Property<int>("FkEquipo")
                        .HasColumnType("int");

                    b.Property<string>("FotoEquipo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MontoGastado")
                        .HasColumnType("int");

                    b.Property<string>("Motivo")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PKHistoricoEquipos");

                    b.HasIndex("EquiposPkEquipo");

                    b.ToTable("HistoricoEquipos");
                });

            modelBuilder.Entity("PowerAppsAplication.Models.HistoricoEquipos", b =>
                {
                    b.HasOne("PowerAppsAplication.Models.Equipos", "Equipos")
                        .WithMany("HistoricoEquipos")
                        .HasForeignKey("EquiposPkEquipo");

                    b.Navigation("Equipos");
                });

            modelBuilder.Entity("PowerAppsAplication.Models.Equipos", b =>
                {
                    b.Navigation("HistoricoEquipos");
                });
#pragma warning restore 612, 618
        }
    }
}
